### ISSUE TITLE
i dont know what is happening but there is something going wrong

### ISSUE THREAD

**Issue by UnrealThingTriesCode** [hendrikbgr/ProtonMail-Account-Creator#32]
**Describe the bug**

**To Reproduce**
1. Choose option x
2. Enter Value x
3. Go until x step

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python Version [e.g. 2.7, 3]
 - Version [e.g. 1.0.0]

**Additional context**
Traceback (most recent call last):
  File "S:\Program Files\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "S:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "S:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "login.py", line 93, in <module>
    driver = webdriver.Chrome(executable_path='/driver/chromedriver', chrome_options=options)
  File "S:\Program Files\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "S:\Program Files\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by hendrikbgr** [comment]
you need to download the chromedriver from the link provided in the error (https://sites.google.com/a/chromium.org/chromedriver/home) - download the version for your current chrome version. Then place the chromedriver file in the driver folder in the project (ProtonMail-Account-Creator/driver)

**Comment by hendrikbgr** [comment]
fix in comment above
